sudo: required
services:
  - docker
language: python
python:
#  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
before_install:
  - "docker build -t slash-coin -f Dockerfile ."
  - "cp slash_coins/app.cfg slash_coins/app_local.cfg"
  - "docker run -d `pwd`/slash_coins/:/opt/slash_coins/config/ -p 8000:8000 --name=slash_coins slash-coin"
install: 
  - "pip install ."
script:
  - "python setup.py travis_test"
after_success:
  - "pip install python-coveralls"
  - "coveralls"